src/main/java/entities/Device.java
package entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;

@XmlRootElement
@Entity
@Table(name = "device", schema = "public")
public class Device implements Serializable {
    private static String STATUS_PUBLISHED = "published";
    private static String STATUS_UNPUBLISHED = "unpublished";
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private String name;
    private String address;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "device")
    @JsonBackReference
    private List<Vote> votes;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "device")
    @JsonBackReference
    private List<Registration> registrations;

    @ManyToOne
    @JoinColumn(name = "userid")
    @JsonManagedReference
    @JsonProperty("owner")
    private User user;

    public Device() {

    }

    public Device(String name, User user) {
        this.name = name;
        this.user = user;
    }

    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Vote> getVotes() {
        return votes;
    }

    public void setVote(Vote vote) {
        this.votes.add(vote);
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Device that = (Device) o;
        return id == that.id &&
                Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, id);
    }

    @Override
    public String toString() {
        return "id: " + id + " name: " + name;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public List<Registration> getRegistrations() {
        return registrations;
    }

    public void setRegistrations(List<Registration> registrations) {
        this.registrations = registrations;
    }
}

src/main/java/entities/Registration.java
package entities;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.util.Date;


@XmlRootElement
@Entity
@Table(name = "registration", schema = "public")
public class Registration implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private long id;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("date_registered")
    private Date dateregistered;

    @ManyToOne
    @JoinColumn(name = "deviceid")
    @JsonManagedReference
    @JsonIgnore
    private Device device;

    @ManyToOne
    @JoinColumn(name = "userid")
    @JsonManagedReference
    @JsonProperty("subscriber")
    private User user;

    private boolean approved;

    public Registration() {
    }

    public Registration(Device device, User subscriber) {
        this.device = device;
        this.user = subscriber;
    }

    public long getId() {
        return id;
    }

    public Device getDevice() {
        return device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    @Override
    public String toString() {
        return "id: " + id + " device_id: " + device.getId();
    }

    public Date getDateregistered() {
        return dateregistered;
    }

    public void setDateregistered(Date registeredDate) {
        this.dateregistered = registeredDate;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }
}

src/main/java/entities/User.java
package entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;


@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@Table(name = "user", schema = "public")
@XmlRootElement
public class User implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String name;
    private String username;
    private String password;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "user")
    @JsonBackReference
    private List<Device> devices;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "user")
    @JsonBackReference
    private List<Registration> registrations;

    public User() {
    }

    public User(String name, String username, String password) {
        this.name = name;
        this.username = username;
        this.password = password;
    }

    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Device> getDevices() {
        return devices;
    }

    public void setDevices(List<Device> devices) {
        this.devices = devices;
    }

    public void setDevice(Device device) {
        this.devices.add(device);
    }

    @Id
    @Column(name = "id")
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, id);
    }

    @Override
    public String toString() {
        return "id: " + id + " name: " + name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @JsonIgnore
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Registration> getRegistrations() {
        return registrations;
    }

    public void setRegistrations(List<Registration> registrations) {
        this.registrations = registrations;
    }

}

src/main/java/entities/Vote.java
package entities;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.util.Objects;


@XmlRootElement
@Entity
@Table(name = "vote", schema = "public")
public class Vote implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private long id;
    private int score;

    @ManyToOne
    @JoinColumn(name = "projectid")
    @JsonManagedReference
    private Device device;

    @Column(name = "ipadress")
    private String ip;

    public long getId() {
        return id;
    }

    @Basic
    @Column(name = "score")
    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    public Device getDevice() {
        return device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ipadress) {
        this.ip = ipadress;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Vote vote = (Vote) o;
        return id == vote.id &&
                Objects.equals(score, vote.score) &&
                Objects.equals(device, vote.device) &&
                Objects.equals(ip, vote.ip);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id, score, ip);
    }

    @Override
    public String toString() {
        return "id: " + id + " score: " + score + " project_id: " + device.getId();
    }
}

src/main/java/ejbs/controller/DeviceController.java
package ejbs.controller;

import ejbs.DeviceDao;
import ejbs.UserDao;
import entities.Device;
import entities.Registration;
import utils.Constants;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named(value = "deviceController")
@SessionScoped
public class DeviceController implements Serializable {
    private static final long serialVersionUID = 1L;

    @EJB
    private DeviceDao deviceDao;

    @EJB
    private UserDao userDao;

    private Device device;


    public void saveDevice() {
        this.deviceDao.create(this.device);
    }

    public List<Device> getAllDevices() {
        return deviceDao.findAll();
    }


    public String mapStatusToCharacter(String status) {
        if (status.equals("ONLINE") || status.equals("AVAILABLE"))
            return "●";

        return "✕";
    }

    public Device showDevice(long deviceId) {
        return deviceDao.find(deviceId);
    }


    public String viewDevice(long deviceId) {
        try {
            this.device = this.deviceDao.find(deviceId);
        } catch (Exception e) {
            return Constants.DEVICES;
        }

        return Constants.DEVICE;
    }

    public List<Device> getUserDevices(long userId) {
        return userDao.getUserDevices(userId);
    }

    public List<Registration> getRegistrations(long deviceId) {
        Device device = deviceDao.find(deviceId);
        return device.getRegistrations();
    }

}

src/main/java/ejbs/controller/SessionController.java
package ejbs.controller;

import ejbs.UserDao;
import entities.User;
import utils.Constants;
import utils.SessionUtil;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import java.io.Serializable;
import java.security.Principal;
import java.util.Map;

@Named(value = "sessionController")
@SessionScoped
public class SessionController implements Serializable {

    private static final long serialVersionUID = 1L;

    private String password;
    private String username;
    private User user;

    @EJB
    private UserDao userDao;

    public String login() throws ServletException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
           request.login(username, password);
            //return Constants.LOGIN;
        }
        catch (ServletException e) {
            context.addMessage(null,
                    new FacesMessage(
                            FacesMessage.SEVERITY_ERROR,
                            "Wrong username nad/or password: " + e.getLocalizedMessage(),
                            null)
            );
            return Constants.LOGIN;
        }
        Principal principal = request.getUserPrincipal();
        this.user = userDao.getUser(principal.getName());
        Map<String, Object> sessionMap = SessionUtil.getSessionMap();
        sessionMap.put(Constants.USER, user);
        SessionUtil.getSession().setAttribute(Constants.USERNAME, this.username);
        return Constants.DEVICES;

    }

    public String logout() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = SessionUtil.getRequest();
        try {
            request.logout();
            this.user = null;
            SessionUtil.getSession().invalidate();
        } catch (ServletException ignored) {
        }
        return Constants.LOGIN;
    }

    public User getUser(){
        return (User)SessionUtil.getSessionMap().get(Constants.USER);
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}

src/main/java/ejbs/controller/UserController.java
package ejbs.controller;

import ejbs.UserDao;
import entities.Device;
import entities.User;
import utils.Constants;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Named(value = "userController")
@RequestScoped
public class UserController implements Serializable {

    private static final long serialVersionUID = 1L;
    @EJB
    private UserDao userDao;

    private User user;
    private Device device;


    public List<User> getUsers() {
        List<User> reverseDeviceList = new ArrayList<>(this.userDao.findAll());
        Collections.reverse(reverseDeviceList);
        return reverseDeviceList;
    }

    public String register() {
        if (userDao.userExists(user.getUsername())) {
            FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage(
                            FacesMessage.SEVERITY_ERROR,
                            "User with this username already exists",
                            null)
            );
            return Constants.REGISTER;
        }
        userDao.createUser(this.user.getName(), this.user.getUsername(), this.user.getPassword());
        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(
                        FacesMessage.SEVERITY_ERROR,
                        "User has been successfully registered",
                        null)
        );
        return Constants.LOGIN;
    }

    public User getUser() {
        if (this.user == null) {
            user = new User();
        }
        return user;
    }

    public Device getDevice() {
        if (this.device == null) {
            device = new Device();
        }
        return device;
    }

}

src/main/webapp/device.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xml:lang="en" lang="en">
<head>
    <title>Devices</title>
    <link rel="stylesheet" href="styles/main.css"/>
</head>

<body>
<ui:composition template="partials/common.xhtml">
    <ui:define name="content">
        <div class="container">
            <div class="devices">
                <table>
                    <tbody>
                    <tr>
                        <td>
                            <h2>My devices</h2>
                        </td>
                    </tr>
                    <ui:repeat value="#{deviceController.getUserDevices(2)}" var="device">
                        <h:form>
                            <tr>
                                <td>
                                    <h:graphicImage width="24px" height="24px" url="img/d.png"/>
                                </td>
                                <td>
                                    <h:outputText value="#{device.name}"/>
                                </td>
                                <td>
                                    <h:outputText class="${device.name}" value="#{deviceController.mapStatusToCharacter('ONLINE')}"/>
                                </td>
                                <td>
                                    <h:commandButton action="${deviceController.viewDevice(device.id)}" value=" device"/>
                                </td>
                            </tr>
                        </h:form>
                    </ui:repeat>
                    </tbody>
                </table>
                <table>
                    <tbody>
                    <tr>
                        <td>
                            <h2>Subscribers</h2>
                        </td>
                    </tr>
                    <ui:repeat value="#{deviceController.getUserDevices(2)}" var="device">
                        <h:form>
                            <tr>
                                <td>
                                    <h:graphicImage width="24px" height="24px" url="img/d.png"/>
                                </td>
                                <td>
                                    <h:outputText value="#{device.name}"/>
                                </td>
                                <td>
                                    <h:outputText class="${device.name}" value="#{deviceController.mapStatusToCharacter('ONLINE')}"/>
                                </td>
                                <td>
                                    <h:commandButton action="${deviceController.getRegistrations(device.id)}" value="subsription"/>
                                </td>
                            </tr>
                        </h:form>
                    </ui:repeat>
                    </tbody>
                </table>
            </div>
        </div>
    </ui:define>
</ui:composition>
</body>
</html>

src/main/webapp/devices.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xml:lang="en" lang="en">
<head>
    <title>Devices</title>
    <link rel="stylesheet" href="styles/main.css"/>
</head>

<body>
<ui:composition template="partials/common.xhtml">
    <ui:define name="content">
        <div class="container">
            <div class="devices">
                <table>
                    <tbody>
                    <tr>
                        <td>
                            <h2>All available devices</h2>
                        </td>
                    </tr>
                    <ui:repeat value="#{deviceController.allDevices}" var="device">
                        <h:form>
                            <tr>
                                <td>
                                    <h:graphicImage width="24px" height="24px" url="img/d.png"/>
                                </td>
                                <td>
                                    <h:outputText value="#{device.name}"/>
                                </td>
                                <td>
                                    <h:outputText class="${device.name}" value="#{deviceController.mapStatusToCharacter('ONLINE')}"/>
                                </td>
                                <td>
                                    <h:commandButton action="${deviceController.viewDevice(device.id)}" value="View device"/>
                                </td>
                            </tr>
                        </h:form>
                    </ui:repeat>
                    </tbody>
                </table>
            </div>
        </div>
    </ui:define>
</ui:composition>
</body>
</html>

src/main/webapp/index.xhtml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml"
      xmlns:h = "http://java.sun.com/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">

<h:head>
    <link rel="stylesheet" href="./styles/main.css" />
</h:head>

<h:body>
    <ui:composition template = "./partials/common.xhtml">
        <ui:define name = "header">
            <h1>IOT Application</h1>
        </ui:define>

        <ui:define name="content">
            <ui:include src="login.xhtml" />
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xml:lang="en" lang="en"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

<head>
    <title>Login</title>
    <link rel="stylesheet" href="styles/main.css"/>
</head>

<h:body>
    <f:view>
        <h:form class="form-login">
            <div class="container">
                <h:inputText a:placeholder="Username" value="#{sessionController.username}"/>
                <h:inputSecret a:placeholder="Password" value="#{sessionController.password}"/>
                <div class="button-row">
                    <h:commandButton action="#{(sessionController.login())}" value="Login"/>
                    <h:button outcome="register" value="Register"/>
                </div>
            </div>

        </h:form>
    </f:view>
</h:body>

</html>

src/main/webapp/register.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
<head>
    <title>Register</title>
    <link rel="stylesheet" href="styles.css"/>
</head>

<h:body>
    <f:view>
        <ui:composition template="partials/common.xhtml">
            <ui:define name="header">
                <h1>IOT Devices</h1>
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <div class="container">

                        <h:inputText a:placeholder="Name" value="#{userController.user.name}" required="true"/>
                        <h:inputText a:placeholder="Username" value="#{userController.user.username}" required="true"/>
                        <h:inputSecret a:placeholder="Password" value="#{userController.user.password}" required="true"/>
                        <div class="button-row">
                            <h:commandButton action="#{userController.register()}" value="Register"/>
                            <h:button outcome="index" value="Back"/>
                        </div>
                    </div>

                </h:form>
            </ui:define>
        </ui:composition>
    </f:view>
</h:body>
</html>

src/main/webapp/subscription.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xml:lang="en" lang="en">
<head>
    <title>Devices</title>
    <link rel="stylesheet" href="styles/main.css"/>
</head>

<body>
<ui:composition template="partials/common.xhtml">
    <ui:define name="content">
        <div class="container">
            <div class="devices">
                <table>
                    <tbody>
                    <tr>
                        <td>
                            <h2>Subscriptions for device  </h2>
                        </td>
                    </tr>
                    <ui:repeat value="#{deviceController.getRegistrations(2)}" var="sub">
                        <h:form>
                            <tr>
                                <td>
                                    <h:outputText value="#{sub.user.name}"/>
                                </td>
                                <td>
                                    <h:outputText value="#{sub.device.name}"/>
                                </td>
                            </tr>
                        </h:form>
                    </ui:repeat>
                    </tbody>
                </table>
            </div>
        </div>
    </ui:define>
</ui:composition>
</body>
</html>